name: Aaron James Nicolas
favicon: null
layout_spectrum: 0.75166
typography_spectrum: 0.07982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202126'
    - '#f9f9f9'
    - '#c3c9c9'
    - '#6a7787'
    - '#3c454e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
